# Generated by Django 5.2.7 on 2025-11-08 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 20, 1, 9, 502112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
