# Generated by Django 5.2.7 on 2025-11-08 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 20, 4, 28, 258044, tzinfo=datetime.timezone.utc)),
        ),
    ]
